apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 244340579641.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 244340579641.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 477a01ec
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
