---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
        - name: demo-frontend
          image: 244340579641.dkr.ecr.us-east-2.amazonaws.com/demo-frontend:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
